apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-gcp-secrets
  namespace: rabbitmq-qa
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/YOUR_GCP_PROJECT_ID/secrets/rabbitmq-erlang-cookie/versions/latest"
        path: "erlang_cookie" # File name in the mount
      - resourceName: "projects/YOUR_GCP_PROJECT_ID/secrets/rabbitmq-admin-password/versions/latest"
        path: "admin_password" # File name in the mount
    # Optional: if you want to sync these as Kubernetes secrets as well
    # syncSecret:
    #   name: rabbitmq-csi-synced-secret # Name of the K8s secret to create/update
    #   type: Opaque
    #   data:
    #     - objectName: erlang_cookie # Key in the K8s secret, value is content of erlang_cookie file
    #       secretKey: ERLANG_COOKIE # Key in the K8s secret
    #     - objectName: admin_password
    #       secretKey: ADMIN_PASSWORD
